#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Bedrock Cost Keeper - Minimal AWS Setup${NC}"
echo -e "${GREEN}========================================${NC}\n"

# Configuration
STACK_NAME="bedrock-cost-keeper-dev-minimal"
ENVIRONMENT="dev"
REGION="${AWS_REGION:-us-east-1}"
TEMPLATE_FILE="minimal-aws-setup.yaml"

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI is not installed${NC}"
    exit 1
fi

# Check if template file exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    echo -e "${RED}Error: Template file not found: $TEMPLATE_FILE${NC}"
    exit 1
fi

# Check AWS credentials
echo -e "${YELLOW}Checking AWS credentials...${NC}"
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured${NC}"
    echo "Please run: aws configure"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✓ AWS Account ID: $ACCOUNT_ID${NC}\n"

# Generate secrets
echo -e "${YELLOW}Generating secrets...${NC}"
JWT_SECRET=$(openssl rand -base64 32)
PROV_API_KEY=$(openssl rand -base64 32)
echo -e "${GREEN}✓ Secrets generated${NC}\n"

# Check if stack already exists
if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" &> /dev/null; then
    echo -e "${YELLOW}Stack $STACK_NAME already exists. Updating...${NC}"
    OPERATION="update"
else
    echo -e "${YELLOW}Creating new stack $STACK_NAME...${NC}"
    OPERATION="create"
fi

# Deploy stack
echo -e "${YELLOW}Deploying CloudFormation stack...${NC}"
aws cloudformation deploy \
  --template-file "$TEMPLATE_FILE" \
  --stack-name "$STACK_NAME" \
  --parameter-overrides \
    Environment="$ENVIRONMENT" \
    JWTSecretKey="$JWT_SECRET" \
    ProvisioningAPIKey="$PROV_API_KEY" \
  --capabilities CAPABILITY_IAM \
  --region "$REGION"

if [ $? -eq 0 ]; then
    echo -e "\n${GREEN}✓ Stack deployed successfully!${NC}\n"
else
    echo -e "\n${RED}✗ Stack deployment failed${NC}"
    exit 1
fi

# Wait for stack to be ready
echo -e "${YELLOW}Waiting for stack to be ready...${NC}"
aws cloudformation wait stack-${OPERATION}-complete \
  --stack-name "$STACK_NAME" \
  --region "$REGION"

# Fetch and display outputs
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Stack Outputs${NC}"
echo -e "${GREEN}========================================${NC}\n"

OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query 'Stacks[0].Outputs' \
  --output json)

echo "$OUTPUTS" | jq -r '.[] | "\(.OutputKey): \(.OutputValue)"'

# Extract key values for .env file
INFERENCE_PROFILE_ARN=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="InferenceProfileArn") | .OutputValue')
JWT_SECRET_NAME=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="JWTSecretName") | .OutputValue')
PROV_API_SECRET_NAME=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="ProvisioningAPISecretName") | .OutputValue')

# Create .env file snippet
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Environment Configuration${NC}"
echo -e "${GREEN}========================================${NC}\n"

cat > .env.cloudformation << EOF
# Generated by CloudFormation deployment: $(date)
# Stack: $STACK_NAME
# Region: $REGION

# AWS Configuration
AWS_ACCOUNT_ID=$ACCOUNT_ID
AWS_REGION=$REGION

# Inference Profile
SAMPLE_APP_INFERENCE_PROFILE_ARN=$INFERENCE_PROFILE_ARN

# Secrets Manager
JWT_SECRET_NAME=$JWT_SECRET_NAME
PROVISIONING_API_KEY_NAME=$PROV_API_SECRET_NAME
EOF

echo -e "${GREEN}✓ Environment configuration saved to: .env.cloudformation${NC}"
echo -e "${YELLOW}  Copy these values to your .env file in the project root${NC}\n"

cat .env.cloudformation

# Update test config
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Test Configuration${NC}"
echo -e "${GREEN}========================================${NC}\n"

TEST_CONFIG="../../test-client/manual_test_config.json"
if [ -f "$TEST_CONFIG" ]; then
    echo -e "${YELLOW}Updating $TEST_CONFIG...${NC}"
    # Use jq to update the config file
    TMP_FILE=$(mktemp)
    jq --arg arn "$INFERENCE_PROFILE_ARN" \
       --arg jwt "$JWT_SECRET_NAME" \
       --arg prov "$PROV_API_SECRET_NAME" \
       '.inference_profile_arn = $arn | .jwt_secret_name = $jwt | .provisioning_api_key_secret_name = $prov' \
       "$TEST_CONFIG" > "$TMP_FILE" && mv "$TMP_FILE" "$TEST_CONFIG"
    echo -e "${GREEN}✓ Test config updated${NC}\n"
fi

# Verify resources
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Verifying Resources${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo -e "${YELLOW}Checking Inference Profile...${NC}"
PROFILE_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="InferenceProfileId") | .OutputValue')
if aws bedrock get-inference-profile \
    --inference-profile-identifier "$PROFILE_ID" \
    --region "$REGION" &> /dev/null; then
    echo -e "${GREEN}✓ Inference Profile accessible${NC}"
else
    echo -e "${RED}✗ Inference Profile not accessible${NC}"
fi

echo -e "\n${YELLOW}Checking Secrets...${NC}"
if aws secretsmanager get-secret-value \
    --secret-id "$JWT_SECRET_NAME" \
    --region "$REGION" &> /dev/null; then
    echo -e "${GREEN}✓ JWT Secret accessible${NC}"
else
    echo -e "${RED}✗ JWT Secret not accessible${NC}"
fi

if aws secretsmanager get-secret-value \
    --secret-id "$PROV_API_SECRET_NAME" \
    --region "$REGION" &> /dev/null; then
    echo -e "${GREEN}✓ Provisioning API Secret accessible${NC}"
else
    echo -e "${RED}✗ Provisioning API Secret not accessible${NC}"
fi

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}\n"

echo -e "${YELLOW}Next steps:${NC}"
echo "1. Copy values from .env.cloudformation to your project .env file"
echo "2. Update test-client/manual_test_config.json (already updated)"
echo "3. Start local development environment: ./scripts/dynamodb.sh start"
echo "4. Run manual tests: cd test-client && python manual_test.py"
echo ""
