AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager resources for Bedrock Cost Keeper'

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

  JWTSecretKey:
    Type: String
    Description: Base64-encoded JWT secret key (32 bytes)
    NoEcho: true

  ProvisioningAPIKey:
    Type: String
    Description: Base64-encoded provisioning API key (32 bytes)
    NoEcho: true

Resources:
  # KMS key for encrypting secrets
  SecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for Bedrock Cost Keeper secrets - ${Environment}'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow ECS tasks to decrypt
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow Secrets Manager to use the key
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:GenerateDataKey'
              - 'kms:CreateGrant'
            Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: bedrock-cost-keeper

  SecretsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/bedrock-cost-keeper-${Environment}'
      TargetKeyId: !Ref SecretsKMSKey

  # JWT Secret Key
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'bedrock-cost-keeper/jwt-secret-${Environment}'
      Description: JWT secret key for token signing
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Ref JWTSecretKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: bedrock-cost-keeper

  # JWT Secret Rotation Schedule (90 days)
  JWTSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref JWTSecret
      RotationRules:
        AutomaticallyAfterDays: 90

  # Provisioning API Key
  ProvisioningAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'bedrock-cost-keeper/provisioning-api-key-${Environment}'
      Description: API key for provisioning endpoints
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Ref ProvisioningAPIKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: bedrock-cost-keeper

  # Provisioning API Key Rotation Schedule (90 days)
  ProvisioningAPISecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref ProvisioningAPISecret
      RotationRules:
        AutomaticallyAfterDays: 90

Outputs:
  SecretsKMSKeyId:
    Description: KMS Key ID for secrets encryption
    Value: !Ref SecretsKMSKey
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyId'

  SecretsKMSKeyArn:
    Description: KMS Key ARN for secrets encryption
    Value: !GetAtt SecretsKMSKey.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyArn'

  JWTSecretArn:
    Description: ARN of the JWT secret
    Value: !Ref JWTSecret
    Export:
      Name: !Sub '${AWS::StackName}-JWTSecretArn'

  ProvisioningAPISecretArn:
    Description: ARN of the provisioning API key secret
    Value: !Ref ProvisioningAPISecret
    Export:
      Name: !Sub '${AWS::StackName}-ProvisioningAPISecretArn'
